<a href="https://colab.research.google.com/github/behdad13/NLP_Basics/blob/main/numpy_crash_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

In [ ]:
import numpy as np

##np.array

In [ ]:
l = [1,2,3,4,5]

In [ ]:
np_a = np.array(l)
print(type(1), type(np_a))

<class 'int'> <class 'numpy.ndarray'>


In [ ]:
np_a.shape

(5,)

In [ ]:
l.append('sting')
np_a = np.array(l)
np_a

array(['1', '2', '3', '4', '5', 'sting'], dtype='<U21')

In [ ]:
#concatenation of two lists
l1 = ['a','b','c']
l2 = l + l1
print(l2)
l3 = l2 + [20]
print(l3)

[1, 2, 3, 4, 5, 'sting', 'a', 'b', 'c']
[1, 2, 3, 4, 5, 'sting', 'a', 'b', 'c', 20]


In [ ]:
#list of list
l4 = [[1, 2], [2, 3], [4, 5]]
np2d = np.array(l4)
print(np2d.shape)
print(np2d)

(3, 2)
[[1 2]
 [2 3]
 [4 5]]


In [ ]:
np2d = np.array(l4, dtype='float')
np2d

array([[1., 2.],
       [2., 3.],
       [4., 5.]])

In [ ]:
#convert to str
np2d = np2d.astype('str')

In [ ]:
np2d[1][1] + str(20)

'3.020'

## `np.nan` and `np.inf`

In [ ]:
np.inf == np.inf

True

In [ ]:
np.nan == np.nan

False

In [ ]:
#for assigning the inf and nan value, the array should be float.

np2d = np2d.astype('float')

np2d[0][0] = np.inf
np2d[1][1] = np.nan
np2d

array([[inf,  2.],
       [ 2., nan],
       [ 4.,  5.]])

In [ ]:
np.isinf(np2d)

array([[ True, False],
       [False, False],
       [False, False]])

In [ ]:
np.isnan(np2d)

array([[False, False],
       [False,  True],
       [False, False]])

In [ ]:
flag = np.isinf(np2d) | np.isnan(np2d)      # | OR operator
flag

array([[ True, False],
       [False,  True],
       [False, False]])

In [ ]:
np2d[flag] = 0
np2d

array([[0., 2.],
       [2., 0.],
       [4., 5.]])

## Statistical Operation

In [ ]:
np2d

array([[0., 2.],
       [2., 0.],
       [4., 5.]])

In [ ]:
np2d.mean()

2.1666666666666665

In [ ]:
np2d.min()

0.0

In [ ]:
np2d.max()

5.0

In [ ]:
np2d.var()

3.472222222222222

In [ ]:
np2d.std()

1.8633899812498247

In [ ]:
np.median(np2d)

2.0

## shape, Rehape(), Revel()

In [ ]:
np2d.shape

(3, 2)

In [ ]:
np2d.reshape(2, 3)     # row, column

array([[0., 2., 2.],
       [0., 4., 5.]])

In [ ]:
np2d.reshape(1, 6)     # It is still two-dimensional

array([[0., 2., 2., 0., 4., 5.]])

In [ ]:
#method 1: with ravel()
np2d.reshape(1, 6).ravel()     

#method 2:
np2d.flatten()

array([0., 2., 2., 0., 4., 5.])

## Arrange

In [ ]:
np.arange(1, 5, dtype='float')   #the last one is excluded.

array([1., 2., 3., 4.])

In [ ]:
np.arange(1, 20, step=3,dtype='float')   #the last one is excluded.

array([ 1.,  4.,  7., 10., 13., 16., 19.])

## linspace, logspace

> Indented block



In [ ]:
np.linspace(1, 20, 3) #it seperate the interval equally with the step

array([ 1. , 10.5, 20. ])

In [ ]:
np.logspace(1, 50, 10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

## zeros, ones

In [ ]:
np.zeros([3, 5])      # [raw, column]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros([2, 3, 4])    # [raw, column]

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.ones([1, 3])        # [raw, column]

array([[1., 1., 1.]])

## tile, repeat

In [ ]:
np.tile([1, 3, 4], 3) #repeat the array n times

array([1, 3, 4, 1, 3, 4, 1, 3, 4])

In [ ]:
np.repeat([1, 3, 4], 3)   #repeat each items of the array n times

array([1, 1, 1, 3, 3, 3, 4, 4, 4])

## random

In [ ]:
np.random.rand(3, 4)

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01, 4.19194514e-01, 6.85219500e-01]])

In [ ]:
np.random.seed(42)  #fixing random number - put it in a particular cell
np_1 = np.random.randint(0, 10, [3, 4]) #int random array [] between 0 and 10 

## unique

In [ ]:
np.unique(np_1)  #return unique values

array([2, 3, 4, 6, 7, 9])

In [ ]:
np.unique(np_1, return_counts=True)  #return unique values with the counter

(array([2, 3, 4, 6, 7, 9]), array([1, 2, 2, 3, 3, 1]))

## where

In [ ]:
arr = np.array([8, 10, 12, 16, 19, 20, 8, 6, 4, 2])
arr

array([ 8, 10, 12, 16, 19, 20,  8,  6,  4,  2])

In [ ]:
index = np.where(arr > 10) #return the positions

In [ ]:
arr[index]

array([12, 16, 19, 20])

In [ ]:
#or 
arr[arr>10]

array([12, 16, 19, 20])

In [ ]:
index = np.where(arr == 10) #return the positions
arr[index]

array([10])

In [ ]:
arr[arr==10]

array([10])

## Argmax, max, argmin, min

In [ ]:
arr.max()   #return the max value

20

In [ ]:
arr.argmax()  #return the postion

5

In [ ]:
arr.min()

2

In [ ]:
arr.argmin()

9

## read and write

In [ ]:
np_2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.savetxt('np_2.csv', np_2, delimiter=',')

In [ ]:
np.loadtxt('np_2.csv', delimiter=',')

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

## concatination

In [ ]:
np_a = np.array([1, 2, 3, 4])

In [ ]:
np_b = np.array([4, 5, 6, 7])

In [ ]:
np.concatenate([np_a, np_b], axis = 0)    # concatenation of two arrays

array([1, 2, 3, 4, 4, 5, 6, 7])

In [ ]:
np.vstack([np_a, np_b])  #vertical concatination  

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [ ]:
np.hstack([np_a, np_b])  #horizontal concatination

array([1, 2, 3, 4, 4, 5, 6, 7])

## sort 


In [ ]:
np_a.sort()

In [ ]:
np_a

array([1, 2, 3, 4])

## Working with dates

In [ ]:
d = np.datetime64('2020-09-01 23:34:24')

In [ ]:
d

numpy.datetime64('2020-09-01T23:34:24')

In [ ]:
d + 10 

numpy.datetime64('2020-09-01T23:34:34')

In [ ]:
oneday = np.timedelta64(1, 'D')      # one day 

In [ ]:
oneday

numpy.timedelta64(1,'D')

In [ ]:
d + oneday 

numpy.datetime64('2020-09-02T23:34:24')

In [ ]:
oneminute = np.timedelta64(1, 'm')

In [ ]:
d + oneminute 

numpy.datetime64('2020-09-01T23:35:24')